# specialai:idle_ai.toml
# 此配置文件包含闲置行为的选项；即怪物在“无聊”时采取的行动。

  # 实体列表（Entity List）字段格式：[ "命名空间:实体类型 值1 值2 ...", ... ]
  # Block List 字段格式：[ "命名空间:方块名[属性1=值1,...]", ... ]
  # 优先级顺序：具体条目 > 标签条目 > 命名空间条目 > 默认值


# Category: idle_general (闲置行为通用设置)
# 影响怪物所有闲置行为（破坏和互动）的选项。

  # 怪物瞄准方块时的触及距离（从眼睛高度计算）。玩家的触及距离约为 4.5。
  # <数值> 范围: ≥ 0.0, 默认: 3.5
  idle_general.reach = 3.5

  # 怪物搜索目标方块的水平（xz平面）和垂直（y轴）范围。
  # <整数> 范围: ≥ 1, 默认: 12
  idle_general.scan_range.horizontal = 12
  # <整数> 范围: ≥ 1, 默认: 6
  idle_general.scan_range.vertical = 6

  # 每次方块扫描之间的刻数间隔。
  # <整数> 范围: ≥ 1, 默认: 2
  idle_general.scan_delay = 2
  # 每只怪物在每次“scan_delay”扫描时随机搜索的方块数量。
  # <整数> 范围: ≥ 1, 默认: 32
  idle_general.scan_count = 32
  # 所有怪物在单刻内可以搜索的最大方块总数。0 为无限制。
  # <整数> 范围: ≥ 0, 默认: 3000
  idle_general.global_scan_count = 3000


# Category: idle_griefing (闲置破坏行为)
# 自定义怪物在闲置时破坏方块的行为。

  # 可以获得被动破坏 AI 的怪物列表及其获得几率。
  # <实体列表> 格式: [ "命名空间:实体类型 几率", ... ]
  idle_griefing.entities.whitelist = [
    "minecraft:zombie 1.0",
    "minecraft:creeper 1.0"
  ]
  idle_griefing.entities.blacklist = []

  # 如果为 true，怪物只会破坏它们拥有对应采集工具的方块。
  # 例如：它们只有在手持镐子时才会破坏熔炉。
  # <布尔值> 默认: true
  idle_griefing.requires_tools = true

  # 如果为 true，被怪物破坏的方块会掉落物品。
  # <布尔值> 默认: true
  idle_griefing.leaves_drops = true
  # 如果为 true，方块被破坏时会播放巨大的碎裂声（原版木门破碎声），且无视距离均可听到。
  # <布尔值> 默认: false
  idle_griefing.break_sound = false

  # 怪物破坏方块的速度倍率，相对于玩家的挖掘速度。
  # <数值> 范围: ≥ 0.0, 默认: 0.5
  idle_griefing.break_speed = 0.5
  # 如果为 true，爬行者会因为没有手去拆方块而感到愤怒，并采取它们最擅长的方式（自爆）。
  # <布尔值> 默认: true
  idle_griefing.mad_creepers = true
  # 如果启用了 'mad_creepers'，爬行者将不会尝试炸毁爆炸抗性等于或高于此值的方块。
  # 具有负抗性的方块（如基岩）会自动忽略。
  # <数值> 范围: ≥ 0.0, 默认: 6.0
  idle_griefing.resistance_threshold = 6.0

  # 如果为 true，闲置破坏 AI 会自动瞄准所有光源（亮度 > 1）。
  # 它会尽力避开自然光源，如火和红石矿石。
  # <布尔值> 默认: true
  idle_griefing.targets.auto_target_lights = true
  # 如果为 true，闲置破坏 AI 会自动瞄准所有床类方块。
  # <布尔值> 默认: true
  idle_griefing.targets.auto_target_beds = true
  # 闲置破坏 AI 可以破坏的特定方块列表。
  idle_griefing.targets.whitelist = [
    "minecraft:farmland",
    "minecraft:beehive",
    "minecraft:crafting_table",
    "minecraft:furnace",
    "minecraft:ladder",
    "minecraft:enchanting_table",
    "minecraft:brewing_stand",
    "minecraft:anvil",
    "minecraft:chipped_anvil",
    "minecraft:damaged_anvil",
    "minecraft:scaffolding",
    "minecraft:loom",
    "minecraft:smoker",
    "minecraft:blast_furnace",
    "minecraft:cartography_table",
    "minecraft:fletching_table",
    "minecraft:grindstone",
    "minecraft:smithing_table",
    "minecraft:stonecutter",
    "twilightforest:iron_ladder",
    "immersiveengineering:metal_ladder_none",
    "immersiveengineering:metal_ladder_alu",
    "immersiveengineering:metal_ladder_steel",
    "enderio:dark_steel_ladder",
    "enderio:painted_crafting_table",
    "create:andesite_ladder",
    "create:brass_ladder",
    "create:copper_ladder",
    "create:andesite_scaffolding",
    "create:brass_scaffolding",
    "create:copper_scaffolding",
    "securitycraft:reinforced_ladder",
    "securitycraft:reinforced_scaffolding",
    "#minecraft:crops"
  ]
  # 类似于白名单，但如果这些方块带有战利品表标签（Loot Table），则不会被瞄准。
  # 例如：尚未开启的地牢箱子不会被破坏。
  idle_griefing.targets.lootable_list = [
    "minecraft:chest",
    "minecraft:ender_chest",
    "minecraft:trapped_chest",
    "minecraft:barrel",
    "twilightforest:twilight_oak_chest",
    "twilightforest:canopy_chest",
    "twilightforest:mangrove_chest",
    "twilightforest:dark_chest",
    "twilightforest:time_chest",
    "twilightforest:transformation_chest",
    "twilightforest:mining_chest",
    "twilightforest:sorting_chest",
    "iceandfire:ghost_chest",
    "securitycraft:keypad_chest"
  ]
  idle_griefing.targets.blacklist = []


# Category: idle_fiddling (闲置互动行为)
# 自定义怪物的“瞎摆弄”行为（与方块交互，如拉开关、开门）。

  # 可以获得被动互动 AI 的怪物列表及其几率。
  idle_fiddling.entities.whitelist = [
    "minecraft:skeleton 1.0",
    "minecraft:stray 1.0",
    "minecraft:wither_skeleton 1.0",
    "minecraft:zombified_piglin 1.0",
    "minecraft:piglin 1.0"
  ]
  idle_fiddling.entities.blacklist = []

  # 是否自动瞄准所有的拉杆和按钮。
  # <布尔值> 默认: true
  idle_fiddling.targets.auto_target_switches = true
  # 是否自动瞄准所有的非金属门、栅栏门和陷阱门。
  # <布尔值> 默认: true
  idle_fiddling.targets.auto_target_doors = true
  # 闲置互动 AI 可以操作的特定方块列表。
  idle_fiddling.targets.whitelist = [
    "minecraft:repeater",
    "minecraft:comparator",
    "minecraft:tnt",
    "minecraft:cake"
  ]
  idle_fiddling.targets.blacklist = []


# Category: idle_hiding (闲置躲藏行为)
# 自定义怪物的躲藏行为。怪物会爬进容器方块内，并在容器被打开或破坏时弹出。

  # 可以获得被动躲藏 AI 的怪物列表及其几率。
  idle_hiding.entities.whitelist = [
    "minecraft:creeper 1.0",
    "minecraft:spider 1.0"
  ]
  idle_hiding.entities.blacklist = []

  # 带有战利品表（Loot Table）的方块被选作躲藏目标的几率。
  # 例如：默认设置下，只有 25% 的未开启地牢箱子可能藏有怪物。
  # <数值> 范围: 0.0 ~ 1.0, 默认: 0.25
  idle_hiding.targets.lootable_chance.base = 0.25
  # 在特定环境条件下，带有战利品表的方块被选作躲藏目标的几率异常设置。
  idle_hiding.targets.lootable_chance.exceptions = []
  # 可以躲藏其中的方块列表。注意：只有拥有方块实体（Tile Entities）的方块才能被躲藏。
  idle_hiding.targets.whitelist = [
    "minecraft:chest",
    "minecraft:trapped_chest",
    "minecraft:barrel",
    "twilightforest:twilight_oak_chest",
    "twilightforest:canopy_chest",
    "twilightforest:mangrove_chest",
    "twilightforest:dark_chest",
    "twilightforest:time_chest",
    "twilightforest:transformation_chest",
    "twilightforest:mining_chest",
    "twilightforest:sorting_chest",
    "iceandfire:ghost_chest",
    "securitycraft:keypad_chest"
  ]
  idle_hiding.targets.blacklist = []
