
[darksteel]

	[darksteel.darksteelaxe]
		#每砍伐一个原木消耗的能量
		energyUsePerFelledLog = 1500

	[darksteel.darksteelpickaxe]
		#破坏黑曜石消耗的能量
		obsidianBreakPowerUse = 50
		#挖掘黑曜石时的速度加成
		speedBoostWhenObsidian = 50
		#达到此硬度时使用黑曜石挖掘速度
		useObsidianBreakSpeedAtHardness = 30

	[darksteel.upgrades]
		#铲子升级激活成本
		spoonActivationCost = 4
		#叉子升级激活成本
		forkActivationCost = 4
		#直接升级激活成本
		directActivationCost = 4

		[darksteel.upgrades.empowered]
			#效率加成
			efficiencyBoost = 2
			#每点伤害消耗的能量
			energyUsePerDamagePoint = 750
			#1级激活成本
			activationCost_l1 = 4
			#1级伤害吸收几率
			damageAbsorptionChance_l1 = 0.5
			#1级最大能量
			maxEnergy_l1 = 100000
			#2级激活成本
			activationCost_l2 = 8
			#2级伤害吸收几率
			damageAbsorptionChance_l2 = 0.6
			#2级最大能量
			maxEnergy_l2 = 150000
			#3级激活成本
			activationCost_l3 = 12
			#3级伤害吸收几率
			damageAbsorptionChance_l3 = 0.7
			#3级最大能量
			maxEnergy_l3 = 250000
			#4级激活成本
			activationCost_l4 = 16
			#4级伤害吸收几率
			damageAbsorptionChance_l4 = 0.85
			#4级最大能量
			maxEnergy_l4 = 1000000

		[darksteel.upgrades.explosive]
			#爆破每方块消耗的能量
			explosiveEnergyPerBlock = 30
			#爆破I激活成本
			explosiveActivationCostI = 8
			#爆破I等级
			explosiveI = 1
			#爆破II激活成本
			explosiveActivationCostII = 12
			#爆破II等级
			explosiveII = 2
			#穿透爆破I激活成本
			explosivePenetrationActivationCostI = 8
			#穿透爆破I等级
			explosivePenetrationI = 1
			#穿透爆破II激活成本
			explosivePenetrationActivationCostII = 12
			#穿透爆破II等级
			explosivePenetrationII = 2

