
#通用机械发电机配置。此配置在服务器和客户端之间同步。
[generators]
	#影响注入速率、最高温度和点火温度。
	energyPerFusionFuel = "10000000"
	#太阳能发电机的峰值输出。注意：在某些极端环境中可能超过此值。
	solarGeneration = "50"
	#高级太阳能发电机的峰值输出。注意：在某些极端环境中可能超过此值。
	advancedSolarGeneration = "300"

	#生物发电机设置
	[generators.bio_generator]
		#生物发电机每刻产生的能量（焦耳）。
		bioGeneration = "350"
		#生物发电机中流体储罐的容量（mB）。
		#Range: > 1
		tankCapacity = 24000

	#热力发电机设置
	[generators.heat_generator]
		#热力发电机每刻产生的能量（焦耳）。heatGeneration + heatGenerationLava * lavaSides + heatGenerationNether。注意：lavaSides是相邻熔岩的面数，如果方块本身含有熔岩也算在内，最多可达7个"面"。
		heatGeneration = "200"
		#相邻熔岩对热力发电机的效果倍数。
		heatGenerationLava = "30"
		#如果热力发电机处于"超高温"维度（原版中仅指下界），则增加此能量（焦耳）。
		heatGenerationNether = "100"
		#热力发电机中流体储罐的容量（mB）。
		#Range: > 1
		tankCapacity = 24000
		#消耗的熔岩量（mB），用于向热力发电机传输heatGeneration焦耳的能量。
		heatGenerationFluidRate = 10

	#燃气发电机设置
	[generators.gas_generator]
		#燃气发电机中气体储罐的容量（mB）。
		#Range: 1 ~ 9223372036854775807
		tankCapacity = 18000
		#燃气发电机中每mB乙烯燃烧的刻数。
		#Range: > 1
		ethyleneBurnTicks = 40
		#计算乙烯能量密度的倍数（1 mB氢气 + 2 * bioGeneration * densityMultiplier）。
		ethyleneDensityMultiplier = "40"

	#涡轮机设置
	[generators.turbine]
		#每个涡轮线圈上每个叶片的叶片数。
		#Range: 1 ~ 12
		turbineBladesPerCoil = 4
		#蒸汽排入涡轮机的速率。
		#Range: 0.1 ~ 1024000.0
		turbineVentGasFlow = 32000.0
		#蒸汽分散到涡轮机的速率。
		#Range: 0.1 ~ 1024000.0
		turbineDisperserGasFlow = 1280.0
		#涡轮机每个方块贡献到总能量容量的能量（J）。最大值 = 体积 * energyCapacityPerVolume
		energyCapacityPerVolume = "16000000"
		#涡轮机蒸汽腔每个方块贡献到体积的气体量（mB）。最大值 = 体积 * gasPerTank
		#Range: 1 ~ 1773043451913643
		gasPerTank = 64000
		#蒸汽在涡轮机中冷凝的速率。
		#Range: 1 ~ 2000000
		condenserRate = 64000

	#风力发电机设置
	[generators.wind_generator]
		#风力发电机的最小基础发电值。
		windGenerationMin = "60"
		#风力发电机的最大基础发电值。
		generationMax = "480"
		#影响风力发电机发电量的最小Y值。此值会被限制在世界最小高度。
		#Range: -2032 ~ 2030
		minY = 24
		#影响风力发电机发电量的最大Y值。此值会被限制在世界逻辑高度。
		maxY = 2031
		#风力发电机不会发电的维度ID列表。
		windGenerationDimBlacklist = []

	#聚变反应堆设置
	[generators.fusion_reactor]
		#从外壳散发的热量转换为焦耳的比例。
		#Range: 0.0 ~ 1.0
		thermocoupleEfficiency = 0.05
		#可从外壳传递到所有非水源的热量比例。将影响最大热量、向热力导体的热传递和发电量。
		#Range: 0.001 ~ 1.0
		casingThermalConductivity = 0.1
		#使用水冷时从外壳散发到水的热量比例。将影响最大热量和蒸汽生成。
		#Range: 0.0 ~ 1.0
		waterHeatingRatio = 0.3
		#聚变反应堆可存储的燃料量（mB）。
		#Range: 2 ~ 1000000
		fuelCapacity = 1000
		#聚变反应堆可存储的能量（J）。
		energyCapacity = "1000000000"
		#聚变反应堆每注入速率可存储的水量（mB）。最大值 = injectionRate * waterPerInjection
		#Range: 1 ~ 21913098
		waterPerInjection = 1000000
		#聚变反应堆每注入速率可存储的蒸汽量（mB）。最大值 = injectionRate * steamPerInjection
		#Range: 1 ~ 94116041192395671
		steamPerInjection = 100000000

	#黑腔室设置
	[generators.hohlraum]
		#黑腔室容量（mB）。
		#Range: 1 ~ 9223372036854775807
		maxGas = 10
		#黑腔室每刻可接受的DT燃料量。
		#Range: 1 ~ 9223372036854775807
		fillRate = 1

	#裂变反应堆设置
	[generators.fission_reactor]
		#每完整mB裂变燃料产生的能量（热量形式）。
		energyPerFissionFuel = "1000000"
		#每个外壳方块增加到裂变反应堆的热容量。增加此值需要更多能量来提高反应堆温度。
		#Range: 1.0 ~ 1000000.0
		casingHeatCapacity = 1000.0
		#达到100%沸腾效率所需的裂变反应堆燃料组件平均表面积。数值越高越难冷却反应堆。
		#Range: 1.0 ~ 1.7976931348623157E308
		surfaceAreaTarget = 4.0
		#是否允许裂变反应堆发生灾难性熔毁。如果禁用，反应堆将关闭而不是熔毁，直到损伤等级降低才能重新开启。
		meltdownsEnabled = true
		#熔毁发生时爆炸的半径。
		#Range: 1.0 ~ 500.0
		meltdownRadius = 8.0
		#损伤超过100%后发生熔毁的几率。随着损伤继续增加会线性缩放。
		#Range: 0.0 ~ 1.0
		meltdownChance = 0.001
		#熔毁期间燃料/废料内容物的辐射倍数。
		#Range: 0.1 ~ 1000000.0
		meltdownRadiationMultiplier = 50.0
		#熔毁后重置反应堆的损伤值。
		#Range: 0.0 ~ 100.0
		postMeltdownDamage = 75.0
		#裂变反应堆的默认燃烧速率。
		#Range: 0.001 ~ 1.0
		defaultBurnRate = 0.1
		#每个燃料组件增加的燃烧速率。最大燃烧速率 = fuelAssemblies * burnPerAssembly
		#Range: 1 ~ 1000000
		burnPerAssembly = 1
		#每个组件贡献到燃料和废料容量的燃料量（mB）。最大值 = fuelAssemblies * maxFuelPerAssembly
		#Range: 1 ~ 2251799813685247
		maxFuelPerAssembly = 8000
		#裂变反应堆每个方块贡献到体积的冷却剂量（mB）。最大值 = 体积 * cooledCoolantPerTank
		#Range: 1 ~ 368224
		cooledCoolantPerTank = 100000
		#裂变反应堆每个方块贡献到体积的加热冷却剂量（mB）。最大值 = 体积 * heatedCoolantPerTank
		#Range: 1000 ~ 1581510980256305
		heatedCoolantPerTank = 1000000

