
#通用机械发电机装备配置。此配置从服务器同步到客户端。
[generators-gear]

	#元套装设置
	[generators-gear.mekasuit]
		#护腿每刻每度（高于环境温度）每升级的地热充电速率（焦耳）。此值根据元套装护腿浸入的程度按比例降低。火被视为约200K高于环境温度，熔岩温度为1,000K高于环境温度。
		geothermalChargingRate = "10.5000"

		[generators-gear.mekasuit.damage_absorption]
			#安装最大地热发电单元的元套装护腿可抵消的热量伤害百分比。此数值根据实际安装的单元数量线性降低。
			#Range: 0.0 ~ 1.0
			heatDamageReductionRatio = 0.8

