
["YUNG's Better Strongholds"]

	###########################################################################################################
	## 通用设置
	###########################################################################################################
	["YUNG's Better Strongholds".General]
		# 要塞各处蜘蛛网的生成率
		# 默认值: 0.1
		"Cobweb Spawn Rate (NORMAL)" = 0.1
		# 图书馆刷怪笼周围蜘蛛网的生成率
		# 默认值: 0.3
		"Cobweb Spawn Rate (SPAWNER)" = 0.3
		# 要塞火把的生成率
		# 默认值: 0.1
		"Torch Spawn Rate" = 0.1
		# 要塞灯笼的生成率
		# 默认值: 0.2
		"Lantern Spawn Rate" = 0.2

