
["YUNG's Better Dungeons"]

	###########################################################################################################
	## 通用设置
	###########################################################################################################
	["YUNG's Better Dungeons".General]
		# 地牢是否可以放置骷髅头颅和其他生物头颅
		# 此选项可能对某些整合包作者有用
		# 默认值: true
		#
		"Enable Skulls & Heads" = true
		# 某些地牢可能会罕见地生成下界相关方块，如灵魂沙、灵魂营火和灵魂灯笼
		# 注意这些方块纯粹是装饰性的 - 不会有远古残骸这种影响进度的东西
		# 设为false可防止任何下界相关方块在地牢中生成
		# 此选项可能对某些整合包作者有用
		# 默认值: true
		#
		"Enable Nether Blocks in Dungeons" = true

	###########################################################################################################
	## 僵尸地牢设置
	###########################################################################################################
	["YUNG's Better Dungeons"."Zombie Dungeons"]
		# 尝试生成地表入口楼梯时可检测的最远距离
		# 设置太大可能会导致问题
		# 默认值: 20
		#
		"Zombie Dungeon Surface Entrance Staircase Max Length" = 20

	###########################################################################################################
	## 小型地牢设置
	###########################################################################################################
	["YUNG's Better Dungeons"."Small Dungeons"]
		# 单个小型地牢可生成的旗帜最大数量
		# 默认值: 2
		#Range: 0 ~ 8
		"Small Dungeon Max Banner Count" = 2
		# 单个小型地牢保证生成的箱子最小数量
		# 默认值: 1
		"Small Dungeon Min Chest Count" = 1
		# 单个小型地牢可生成的箱子最大数量
		# 默认值: 2
		"Small Dungeon Max Chest Count" = 2
		# 小型地牢是否可以在角落罕见地放置矿石方块
		# 如果设为false，作为角落装饰的矿石方块将被替换为空气
		# 默认值: true
		#
		"Allow Ore Blocks in Corners" = true

	###########################################################################################################
	## 小型下界地牢设置
	## 默认关闭
	###########################################################################################################
	["YUNG's Better Dungeons"."Small Nether Dungeons"]
		# 是否生成小型下界地牢
		# 默认值: false
		"Enable Small Nether Dungeons" = false
		# 小型下界地牢刷怪笼生成的凋灵骷髅是否有几率掉落凋灵骷髅头颅
		# 默认值: true
		"Wither Skeletons From Spawners Drop Wither Skeleton Skulls" = true
		# 小型下界地牢刷怪笼生成的烈焰人是否有几率掉落烈焰棒
		# 默认值: true
		"Blazes From Spawners Drop Blaze Rods" = true
		# 单个小型下界地牢可生成的旗帜最大数量
		# 默认值: 2
		#Range: 0 ~ 8
		"Small Nether Dungeon Max Banner Count" = 2

