
["YUNG's Better Nether Fortresses"]

	###########################################################################################################
	## 通用设置
	###########################################################################################################
	["YUNG's Better Nether Fortresses".General]
		# 是否禁用原版下界堡垒
		# 默认值: true
		#
		"Disable Vanilla Nether Fortresses" = true

