
["YUNG's Better Desert Temples"]

	###########################################################################################################
	## 通用设置
	###########################################################################################################
	["YUNG's Better Desert Temples".General]
		# 是否禁用原版沙漠神殿
		# 默认值: true
		#
		"Disable Vanilla Pyramids" = true
		# 沙漠神殿未被清理时是否对玩家施加挖掘疲劳效果
		# 默认值: true
		#
		"Apply Mining Fatigue" = true

