
["YUNG's Better Ocean Monuments"]

	###########################################################################################################
	## 通用设置
	###########################################################################################################
	["YUNG's Better Ocean Monuments".General]
		# 是否禁用原版海底神殿
		# 默认值: true
		#
		"Disable Vanilla Ocean Monuments" = true

